# This is the definitive blueprint for Render.
# It declaratively links to your existing database and web service.
databases:
  - name: service-bay-db  # MUST match the name of your existing database exactly
    databaseName: service_bay
    user: service_bay_user
    plan: free
    region: frankfurt

services:
  - type: web
    name: service-bay-api
    env: python
    region: frankfurt
    plan: free
    branch: main
    rootDir: backend

    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate

    startCommand: gunicorn service_bay_api.wsgi:application --bind 0.0.0.0:$PORT

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: service-bay-db
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: service_bay_api.settings
      - key: WEB_CONCURRENCY
        value: 4
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
