services:
  - type: web
    name: service-bay-api
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate --noinput
      python manage.py createadmin
    startCommand: gunicorn service_bay_api.wsgi:application
    envVars:
      - key: DATABASE_URL
        value: postgresql://service_bay_user:RZPyZJuvRizKZbuKGJaSccxNX5ct5wV0@dpg-d431ch8dl3ps73a11lf0-a/service_bay
      - key: SECRET_KEY
        value: your-secret-key-here
      - key: DEBUG
        value: False
      - key: ADMIN_EMAIL
        value: waynendi004@gmail.com
      - key: ADMIN_PASSWORD
        value: YourStrongPassword123
