services:
  - type: web
    name: service-bay-api
    env: python
    region: frankfurt
    rootDir: backend
    plan: free
    
    buildFilter:
      paths:
        - "backend/**"
        
    buildCommands:
      - pip install -r requirements.txt
      - python manage.py migrate
      
    startCommand: "gunicorn service_bay_api.wsgi:application --bind 0.0.0.0:$PORT"
    
    envVars:
      - key: DATABASE_URL
        # This securely connects to the database we created in Step 1
        fromService:
          type: psql
          name: service-bay-db # Must match the name you gave your DB
      - key: DJANGO_SETTINGS_MODULE
        value: service_bay_api.settings
      - key: WEB_CONCURRENCY
        value: 4
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False

