# This is the definitive blueprint for Render.
# It declaratively creates both the database and the web service.

databases:
  - name: service-bay-db
    databaseName: service_bay
    user: service_bay_user
    plan: free
    region: frankfurt

services:
  - type: web
    name: service-bay-api
    env: python
    region: frankfurt
    plan: free
    branch: main
    rootDir: backend
    
    # --- THIS IS THE FIX (PART 1) ---
    # The buildCommands must only install packages and migrate the database.
    buildCommands: |
      pip install -r requirements.txt
      python manage.py migrate
      
    startCommand: "gunicorn service_bay_api.wsgi:application --bind 0.0.0.0:$PORT"
    
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: service-bay-db # This must match your database name
          # --- THIS IS THE FIX (PART 2) ---
          # We must specify 'connectionString' as the property.
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: service_bay_api.settings
      - key: WEB_CONCURRENCY
        value: 4
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"