# This is the definitive blueprint for Render.
# It defines ONLY the web service and connects to your EXISTING database.

services:
  - type: web
    name: service-bay-api
    env: python
    region: frankfurt
    plan: free
    branch: main
    rootDir: backend
    
    buildCommands: |
      pip install -r requirements.txt
      python manage.py migrate
      
    startCommand: "gunicorn service_bay_api.wsgi:application --bind 0.0.0.0:$PORT"
    
    envVars:
      - key: DATABASE_URL
        fromService:
          type: psql
          name: service-bay-db # This MUST match the name of your EXISTING database
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: service_bay_api.settings
      - key: WEB_CONCURRENCY
        value: 4
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
        