# render.yaml
# Web service only — uses existing Render database
services:
  - type: web
    name: service-bay-api
    env: python
    region: frankfurt
    plan: free
    branch: main
    rootDir: backend

    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate

    startCommand: gunicorn service_bay_api.wsgi:application --bind 0.0.0.0:$PORT

    envVars:
      - key: DATABASE_URL
        value: <YOUR DATABASE INTERNAL URL HERE>
      - key: DJANGO_SETTINGS_MODULE
        value: service_bay_api.settings
      - key: WEB_CONCURRENCY
        value: 4
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
