databases:
  - name: service-bay-db
    databaseName: service_bay
    user: service_bay_user
    plan: free
    region: frankfurt

services:
  - type: web
    name: service-bay-api
    env: python
    region: frankfurt
    plan: free
    rootDir: backend
    
    buildFilter:
      paths:
        - "backend/**"
        
    buildCommands:
      - pip install -r requirements.txt
      - python manage.py migrate
      
    startCommand: "gunicorn service_bay_api.wsgi:application --bind 0.0.0.0:$PORT"
    
    envVars:
      - key: DATABASE_URL
        fromService:
          type: database
          name: service-bay-db
      - key: DJANGO_SETTINGS_MODULE
        value: service_bay_api.settings
      - key: WEB_CONCURRENCY
        value: 4
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"

